Write a class that calculates the similarity between the decoder context vector and the encoder context vectors. In this task, we define similarity as $ sim(h,s)=h 
T
 s=∑h 
i
​
 s 
i$ 

Fill in the gaps in the code:

```python

import torch
import torch.nn as nn


class Similarity1(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, encoder_states: torch.Tensor, decoder_state: torch.Tensor):
        # encoder_states.shape = [T, N]
        # decoder_state.shape = [N]
        # YOUR CODE HERE

```

In [131]:
import torch
import torch.nn as nn


class Similarity1(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, encoder_states: torch.Tensor, decoder_state: torch.Tensor):
        # encoder_states.shape = [T, N]
        # decoder_state.shape = [N]
        # YOUR CODE HERE
        sim = torch.tensordot(encoder_states, decoder_state, dims=1)

        return sim


In [117]:
E = torch.rand(5, 2)
D = torch.rand(2)

In [118]:
E

tensor([[0.0518, 0.7256],
        [0.9012, 0.5781],
        [0.0376, 0.4927],
        [0.2336, 0.8936],
        [0.2058, 0.6470]])

In [119]:
D

tensor([0.6457, 0.8857])

In [132]:
S = Similarity1()

S.forward(E,D)

tensor([0.6761, 1.0939, 0.4607, 0.9423, 0.7059])

In [104]:
import torch
import torch.nn as nn


class Similarity2(nn.Module):
    def __init__(self, encoder_dim: int, decoder_dim: int, intermediate_dim: int):
        super().__init__()

        self.fc1 = nn.Linear(encoder_dim, intermediate_dim)
        self.fc2 = nn.Linear(decoder_dim, intermediate_dim)
        self.fc3 = nn.Linear(intermediate_dim, 1)
        self.tanh = nn.Tanh()

    def forward(self, encoder_states: torch.Tensor, decoder_state: torch.Tensor):
        # encoder_states.shape = [T, N]
        # decoder_state.shape = [N]
        # YOUR CODE HERE

        x1 = self.fc1(encoder_states)
        x2 = self.fc2(decoder_state)
        x3 = self.tanh(x1 + x2)
        
        return self.fc3(x3)
            

        

In [109]:
S2 = Similarity2(3, 3, 3)

E = torch.rand(5, 3)
D = torch.rand(3)

S2.forward(E, D)

tensor([[-0.3830],
        [-0.3804],
        [-0.3987],
        [-0.3806],
        [-0.3938]], grad_fn=<AddmmBackward0>)