In [34]:
import torch
import numpy as np
from torch import nn

**Write a function called function01.** It should have the following signature:

```def function01(tensor: torch.Tensor, count_over: str) -> torch.Tensor:```

If count_over is equal to ‘columns’, return the average of the tensor by columns. If it is equal to ‘rows’, return the average by rows. It is guaranteed that the tensor will be a matrix (i.e., it will have dimension 2).

In [35]:
def function01(tensor: torch.Tensor, count_over: str) -> torch.Tensor:
    if count_over == 'columns':

        return tensor.mean(dim=0)

    elif count_over == 'rows':

        return tensor.mean(dim=1)

    else:

        return 0

In [36]:
function01(tensor = torch.rand(2, 3), count_over = 'columns')

tensor([0.4536, 0.9042, 0.2470])

**Write function02.** The function should take a dataset as input—a tensor matrix of object features. Your function should create a tensor vector with weights (let them be uniformly distributed on the interval from 0 to 1) and return them for further training of linear regression without a free coefficient. Make these weights of type float32, as gradients will need to be calculated for them during training (use requires_grad).

Translated with DeepL.com (free version)

In [37]:
def function02(tensor: torch.Tensor) -> torch.Tensor:
    
    return torch.rand(tensor.shape[1], requires_grad=True, dtype=torch.float32)

In [38]:
function02(tensor = torch.rand(2, 3))

tensor([0.0577, 0.2165, 0.5643], requires_grad=True)

**Write the function function03.**** It should accept a tensor matrix with objects and a tensor vector with correct answers. We will solve the regression problem: def function03(x: torch.Tensor, y: torch.Tensor):

Create weights for linear regression (without a free coefficient) inside the function. You can use the function from the previous step. Use gradient descent to select the optimal weights for the input data (use a step length of about 1e-2). Return a tensor vector with the optimal weights from the function. Your trained weights should give an MSE of less than one on the training sample.

In [39]:
def function03(x: torch.Tensor, y: torch.Tensor):
    
    mse = 100
    i = 0
    w = function02(x) 
    
    while mse >= 1:
        
        i += 1

        ax = torch.matmul(x, w)

        mse = torch.mean((ax - y) ** 2)

        if i < 20 or i % 10 == 0:

            print(f'MSE at step {i + 1}: {mse.item():.5f}')

        mse.backward()

        with torch.no_grad():
            
            w -= w.grad * 1e-2
            
        w.grad.zero_()

    return w

In [40]:
n_features = 2   
n_objects = 300

w_true = torch.randn(n_features)
X = (torch.rand(n_objects, n_features) - 0.5) * 5
Y = X @ w_true + torch.randn(n_objects) / 2

In [41]:
function03(X, Y)

MSE at step 2: 0.52499


tensor([0.4266, 0.5838], requires_grad=True)

**Write function04.** It should accept a tensor matrix with objects and a tensor with correct answers. We will solve a regression problem: def function04(x: torch.Tensor, y: torch.Tensor):

Create a fully connected layer inside the function, train this fully connected layer on the input data using gradient descent (use a step length of about 1e-2). Return it from the function. Your fully connected layer should give an MSE on the training sample of less than 0.3.

In [42]:
def function04(x: torch.Tensor, y: torch.Tensor):
    
    mse = 10
    i = 0
    
    layer = nn.Linear(in_features= x.shape[1], out_features=1)
    
    while mse >= 0.3:
        
        i += 1

        ax = layer(x).ravel()

        mse = torch.mean((ax - y) ** 2)

        if i < 20 or i % 10 == 0:

            print(f'MSE at step {i + 1} {mse.item():.5f}')

        mse.backward()

        with torch.no_grad():
            
            layer.weight -= layer.weight.grad * 1e-2
            layer.bias -= layer.bias.grad * 1e-2
            
        layer.zero_grad()

    return layer

In [43]:
function04(X, Y)

MSE at step 2 3.18926
MSE at step 3 2.94244
MSE at step 4 2.71668
MSE at step 5 2.51016
MSE at step 6 2.32123
MSE at step 7 2.14836
MSE at step 8 1.99019
MSE at step 9 1.84545
MSE at step 10 1.71297
MSE at step 11 1.59171
MSE at step 12 1.48071
MSE at step 13 1.37908
MSE at step 14 1.28603
MSE at step 15 1.20081
MSE at step 16 1.12275
MSE at step 17 1.05125
MSE at step 18 0.98574
MSE at step 19 0.92571
MSE at step 20 0.87069
MSE at step 21 0.82026
MSE at step 31 0.49673
MSE at step 41 0.35789
MSE at step 51 0.29629


Linear(in_features=2, out_features=1, bias=True)